### ISSUE TITLE
Does not work on this site :( Not sure why

### ISSUE THREAD

**Issue by ng4ever** [igorlogius/youtube-embed-2-anchor#1]
https://hardforum.com/threads/vampire-the-masquerade-bloodhunt.2013636/#post-1045339517

**Comment by igorlogius** [comment]
That forum sadly does not use the "default" youtube embed markup ...  but a mix of a placeholder ... which gets replaced when you interact with it (click)

```
<span data-s9e-mediaembed-c2l="youtube" data-s9e-mediaembed-c2l-background="linear-gradient(0deg,rgba(0,0,0,0) 0,rgba(0,0,0,0) 72%,rgba(0,0,0,.04) 79%,rgba(0,0,0,.1) 83%,rgba(0,0,0,.25) 88%,rgba(0,0,0,.67) 100%),url(https://i.ytimg.com/vi/QUEpPwjOBnU/hqdefault.jpg) 50% 50% / cover" data-s9e-mediaembed-c2l-oembed-id="QUEpPwjOBnU" data-s9e-mediaembed-c2l-oembed-title="Bloodhunt - Narrative Launch Trailer" data-s9e-mediaembed-iframe="[&quot;allowfullscreen&quot;,&quot;&quot;,&quot;scrolling&quot;,&quot;no&quot;,&quot;allow&quot;,&quot;autoplay&quot;,&quot;src&quot;,&quot;https:\/\/www.youtube.com\/embed\/QUEpPwjOBnU?autoplay=1&quot;]"></span>
```

I dont think i'll change the addon ... for this  special case but ... you can easily this userscript: 

```
(function () {
    let tmp;
    const spans = document.getElementsByTagName('span');
    for(const span of spans) {
try {
        //console.log(iframe.src);
        tmp = span.getAttribute("data-s9e-mediaembed-iframe");
		if(tmp){
		console.log(tmp)
			tmp = JSON.parse(tmp);
			console.log(tmp[7])
			if(tmp){
				a = document.createElement('a');
				a.href = tmp[7];
				a.innerText = a.href;
				span.replaceWith(a);
			}
        }
}catch(e){
console.error(e);
}
    }
}())

```

It doenst replace the posters but i hope that it still fine. 

Hope it helps.

**Comment by ng4ever** [comment]
Still does not work for me :( Not sure why. 

I put this down as the userscript in tampermonkey. 

// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://*/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

let timerID;

function replaceIFramesWithAnchors() {
    let tmp;
    const spans = document.getElementsByTagName('span');
    for(const span of spans) {
        //console.log(iframe.src);
        tmp = span.getAttribute("data-s9e-mediaembed-iframe");
        if(tmp){
            tmp = JSON.parse(tmp);
            if(tmp){
                a = document.createElement("a");
                a.href = tmp[7];
                a.innerText = tmp[7];
                a.target = "_blank";
                span.replaceWith(a);
            }
        }
    }
}

// if we have many mution events, wait until the site has settled
function delayed_onChange(){
    clearTimeout(timerID);
    timerID = setTimeout(replaceIFramesWithAnchors, 500); // todo: maybe there is a better way to determine if the site is settled
}

function init() {
    // start observer
    (new MutationObserver(delayed_onChange)).observe(document.body, { attributes: false, childList: true, subtree: true });
    delayed_onChange();
}

//console.log('reply:', reply);

setTimeout(init, 500); // adding delays ... makes stuff better

**Comment by igorlogius** [comment]
Here the complete Tampermonkey script:

[tampermonkey_scripts.zip](https://github.com/igorlogius/youtube-embed-2-anchor/files/8758516/tampermonkey_scripts.zip)

You can import it via > Utiltities > "Import from file"

**Comment by ng4ever** [comment]
> Here the complete Tampermonkey script:
> 
> [tampermonkey_scripts.zip](https://github.com/igorlogius/youtube-embed-2-anchor/files/8758516/tampermonkey_scripts.zip)
> 
> You can import it via > Utiltities > "Import from file"


Thank you! Greatly appreciated!
